### ISSUE TITLE
Starting Noah correction

### ISSUE THREAD

**Issue by pimoussefrnl** [faustbrian/noah#3]
Hi Brian,

Small correction :)

**It should be:**
`bash ~/noah/noah.sh --start`
**which returns:**
```
==> Starting noah...
==> Start complete!
```

**instead of:**
`bash ~/noah/noah.sh start`
**returns:**
`Usage: noah.sh [options]`

**Comment by faustbrian** [comment]
https://github.com/faustbrian/noah/commit/661a39052ea597719b8db64c51cb80972943d7ce
